openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /signup:
    post:
      tags:
      - user-controller
      operationId: addNewUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /orders/buy:
    post:
      tags:
      - order-controller
      operationId: newOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Orders'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /login:
    post:
      tags:
      - login
      operationId: createAuthenticationToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /items/add:
    post:
      tags:
      - item-controller
      operationId: addNewProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Items'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /customer/add:
    post:
      tags:
      - customer-controller
      operationId: addNewCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /orders/customerId:
    get:
      tags:
      - order-controller
      operationId: getOrdersByCustId_1
      parameters:
      - name: custId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    put:
      tags:
      - order-controller
      operationId: getOrdersByCustId
      parameters:
      - name: custId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    post:
      tags:
      - order-controller
      operationId: getOrdersByCustId_5
      parameters:
      - name: custId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
      - order-controller
      operationId: getOrdersByCustId_4
      parameters:
      - name: custId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    options:
      tags:
      - order-controller
      operationId: getOrdersByCustId_6
      parameters:
      - name: custId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    head:
      tags:
      - order-controller
      operationId: getOrdersByCustId_2
      parameters:
      - name: custId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    patch:
      tags:
      - order-controller
      operationId: getOrdersByCustId_3
      parameters:
      - name: custId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /orders/all:
    get:
      tags:
      - order-controller
      operationId: getAllOrders_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    put:
      tags:
      - order-controller
      operationId: getAllOrders
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    post:
      tags:
      - order-controller
      operationId: getAllOrders_5
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
      - order-controller
      operationId: getAllOrders_4
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    options:
      tags:
      - order-controller
      operationId: getAllOrders_6
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    head:
      tags:
      - order-controller
      operationId: getAllOrders_2
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    patch:
      tags:
      - order-controller
      operationId: getAllOrders_3
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /items/{id}:
    get:
      tags:
      - item-controller
      operationId: getitemById_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Items'
    put:
      tags:
      - item-controller
      operationId: getitemById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Items'
    post:
      tags:
      - item-controller
      operationId: getitemById_5
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Items'
    delete:
      tags:
      - item-controller
      operationId: getitemById_4
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Items'
    options:
      tags:
      - item-controller
      operationId: getitemById_6
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Items'
    head:
      tags:
      - item-controller
      operationId: getitemById_2
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Items'
    patch:
      tags:
      - item-controller
      operationId: getitemById_3
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Items'
  /items/all:
    get:
      tags:
      - item-controller
      operationId: getAllProducts_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    put:
      tags:
      - item-controller
      operationId: getAllProducts
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    post:
      tags:
      - item-controller
      operationId: getAllProducts_5
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
      - item-controller
      operationId: getAllProducts_4
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    options:
      tags:
      - item-controller
      operationId: getAllProducts_6
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    head:
      tags:
      - item-controller
      operationId: getAllProducts_2
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    patch:
      tags:
      - item-controller
      operationId: getAllProducts_3
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /customer/{id}:
    get:
      tags:
      - customer-controller
      operationId: getById_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Customer'
    put:
      tags:
      - customer-controller
      operationId: getById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Customer'
    post:
      tags:
      - customer-controller
      operationId: getById_5
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Customer'
    delete:
      tags:
      - customer-controller
      operationId: getById_4
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Customer'
    options:
      tags:
      - customer-controller
      operationId: getById_6
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Customer'
    head:
      tags:
      - customer-controller
      operationId: getById_2
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Customer'
    patch:
      tags:
      - customer-controller
      operationId: getById_3
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Customer'
  /customer/all:
    get:
      tags:
      - customer-controller
      operationId: getAllCustomers_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    put:
      tags:
      - customer-controller
      operationId: getAllCustomers
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    post:
      tags:
      - customer-controller
      operationId: getAllCustomers_5
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
      - customer-controller
      operationId: getAllCustomers_4
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    options:
      tags:
      - customer-controller
      operationId: getAllCustomers_6
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    head:
      tags:
      - customer-controller
      operationId: getAllCustomers_2
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    patch:
      tags:
      - customer-controller
      operationId: getAllCustomers_3
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /all:
    get:
      tags:
      - user-controller
      operationId: getAllUsers_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    put:
      tags:
      - user-controller
      operationId: getAllUsers
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    post:
      tags:
      - user-controller
      operationId: getAllUsers_5
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
      - user-controller
      operationId: getAllUsers_4
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    options:
      tags:
      - user-controller
      operationId: getAllUsers_6
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    head:
      tags:
      - user-controller
      operationId: getAllUsers_2
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    patch:
      tags:
      - user-controller
      operationId: getAllUsers_3
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        password:
          type: string
        active:
          type: integer
          format: int32
        roles:
          type: string
        permissions:
          type: string
        roleList:
          type: array
          items:
            type: string
        permissionList:
          type: array
          items:
            type: string
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
    Items:
      type: object
      properties:
        id:
          type: integer
          format: int64
        itemNumber:
          type: string
        name:
          type: string
    Orders:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customer:
          $ref: '#/components/schemas/Customer'
        item:
          $ref: '#/components/schemas/Items'
